version: '3.7'

services:
  sut:
    build:
      context: .
      cache_from:
        - homebrew/brew
      args:
        - FORCE_REBUILD=1
    command:
      - sh
      - -xc
      - |
        /home/linuxbrew/.linuxbrew/bin/brew test-bot
        status=$$?
        exit $$status
