sut:
  build: .
  command: "sudo -i -u linuxbrew /home/linuxbrew/.linuxbrew/bin/brew test-bot"
  environment:
    - BUILD_REASON
    - BUILD_REPOSITORY_URI
    - BUILD_SOURCEVERSION
    - HOMEBREW_GITHUB_API_TOKEN
    - SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
    - SYSTEM_PULLREQUEST_TARGETBRANCH
    - TF_BUILD
