sut:
  build: .
  command:
    - sh
    - -xc
    - |
      sudo -E -u linuxbrew /home/linuxbrew/.linuxbrew/bin/brew test-bot
      status=$$?
      cp brew-test-bot.xml /tmp/test-bot/
      exit $$status
  environment:
    - HOME=/home/linuxbrew
    - BUILD_REASON
    - BUILD_REPOSITORY_URI
    - BUILD_SOURCEVERSION
    - HOMEBREW_GITHUB_API_TOKEN
    - SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
    - SYSTEM_PULLREQUEST_TARGETBRANCH
    - TF_BUILD
