inherit_from: ./.rubocop.yml

AllCops:
  Include:
    - '**/*_spec.rb'
  Exclude:
    - '**/vendor/**/*'

NewFormulaAudit:
  Enabled: true

# Intentionally disabled as it doesn't fit with our code style.
RSpec/AnyInstance:
  Enabled: false
RSpec/ImplicitBlockExpectation:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false

# TODO: try to enable these (also requires fixing Homebrew/bundle)
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false

# TODO: try to reduce these (also requires fixing Homebrew/bundle)
RSpec/ExampleLength:
  Max: 75
RSpec/MultipleExpectations:
  Max: 26
RSpec/NestedGroups:
  Max: 5
